SPDX-PackageDownloadLocation = "https://weblate.org/"
SPDX-PackageName = "weblate-fonts"
SPDX-PackageSupplier = "Michal Čihař <michal@weblate.org>"
version = 1

[[annotations]]
path = ["README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  ".gitignore",
  ".pre-commit-config.yaml",
  "biome.json",
  "pyproject.toml",
  "REUSE.toml",
  "setup.cfg",
  "src/weblate_fonts/static/weblate_fonts/source-code-pro.css",
  "src/weblate_fonts/static/weblate_fonts/source-sans-3.css"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/weblate_fonts/static/weblate_fonts/kurinto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright ©2017-2021, Clinton F. Goss"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/weblate_fonts/static/weblate_fonts/source-*/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2010-2024 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'. All Rights Reserved. Source is a trademark of Adobe in the United States and/or other countries."
SPDX-License-Identifier = "OFL-1.1"
