SPDX-PackageDownloadLocation = "https://weblate.org/"
SPDX-PackageName = "weblate-fonts"
SPDX-PackageSupplier = "Michal Čihař <michal@weblate.org>"
version = 1

[[annotations]]
path = ["README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  ".gitignore",
  ".gitmodules",
  ".pre-commit-config.yaml",
  ".weblate",
  ".well-known/*",
  "MANIFEST.in",
  "pyproject.toml",
  "requirements**.txt",
  "REUSE.toml",
  "setup.cfg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "OFL-1.1"
